### ISSUE TITLE
error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment

### ISSUE THREAD

**Issue by MikeTuffin** [jeroenooms/V8#11]
I'm receiving the following error when trying to build from source on Linux:

==> devtools::document(roclets=c('rd', 'namespace'))

Updating V8 documentation
Loading V8
Re-compiling V8
'/usr/lib64/R/bin/R' --vanilla CMD INSTALL  \
  '/home/mike/Documents/kaggle/otto/V8'  \
  --library='/tmp/RtmpqDns3X/devtools_install_1eb8118166e6' --no-R --no-data  \
  --no-help --no-demo --no-inst --no-docs --no-exec --no-multiarch  \
  --no-test-load --preclean 

* installing *source* package ‘V8’ ...
g++ -I/usr/include/R/ -DNDEBUG  -D_FORTIFY_SOURCE=2 -I"/home/mike/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4  -c RcppExports.cpp -o RcppExports.o
** libs
g++ -I/usr/include/R/ -DNDEBUG  -D_FORTIFY_SOURCE=2 -I"/home/mike/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4  -c V8.cpp -o V8.o
V8.cpp: In function ‘void ctx_finalizer(v8::Persistent<v8::Context>*)’:
V8.cpp:32:14: error: ‘class v8::Persistent<v8::Context>’ has no member named ‘Dispose’
     context->Dispose();
              ^
V8.cpp: In function ‘v8::Handle<v8::Script> compile_source(std::string)’:
V8.cpp:40:27: error: ‘New’ is not a member of ‘v8::String’
   Handle<String> source = String::New(src.c_str());
                           ^
V8.cpp: At global scope:
V8.cpp:46:39: error: ‘Arguments’ does not name a type
 static Handle<Value> ConsoleLog(const Arguments& args) {
                                       ^
V8.cpp: In function ‘v8::Handle<v8::Value> ConsoleLog(const int&)’:
V8.cpp:47:26: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
   for (int i=0; i < args.Length(); i++) {
                          ^
V8.cpp:48:5: error: ‘AsciiValue’ is not a member of ‘v8::String’
     String::AsciiValue str(args[i]->ToString());
     ^
V8.cpp:49:20: error: ‘str’ was not declared in this scope
     Rprintf("%s", *str);
                    ^
V8.cpp:52:24: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
   return v8::Undefined();
                        ^
In file included from V8.cpp:16:0:
/usr/include/v8.h:312:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
V8.cpp: At global scope:
V8.cpp:56:40: error: ‘Arguments’ does not name a type
 static Handle<Value> ConsoleWarn(const Arguments& args) {
                                        ^
V8.cpp: In function ‘v8::Handle<v8::Value> ConsoleWarn(const int&)’:
V8.cpp:57:26: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
   for (int i=0; i < args.Length(); i++) {
                          ^
V8.cpp:58:5: error: ‘AsciiValue’ is not a member of ‘v8::String’
     String::AsciiValue str(args[i]->ToString());
     ^
V8.cpp:59:43: error: ‘str’ was not declared in this scope
     Rf_warningcall_immediate(R_NilValue, *str);
                                           ^
V8.cpp:61:24: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
   return v8::Undefined();
                        ^
In file included from V8.cpp:16:0:
/usr/include/v8.h:312:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
V8.cpp: At global scope:
V8.cpp:65:41: error: ‘Arguments’ does not name a type
 static Handle<Value> ConsoleError(const Arguments& args) {
                                         ^
V8.cpp: In function ‘v8::Handle<v8::Value> ConsoleError(const int&)’:
V8.cpp:66:11: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
   if(args.Length()){
           ^
V8.cpp:67:12: error: ‘ThrowException’ is not a member of ‘v8’
     return v8::ThrowException(args[0]);
            ^
V8.cpp:67:37: error: invalid types ‘const int[int]’ for array subscript
     return v8::ThrowException(args[0]);
                                     ^
V8.cpp:69:24: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
   return v8::Undefined();
                        ^
In file included from V8.cpp:16:0:
/usr/include/v8.h:312:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
/usr/include/v8.h: In function ‘ctxptr make_context(bool)’:
/usr/include/v8.h:832:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
V8.cpp:75:15: error: within this context
   HandleScope handle_scope;
               ^
V8.cpp:79:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     global->Set(String::NewSymbol("console"), console);
                 ^
V8.cpp:80:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     console->Set(String::NewSymbol("log"), FunctionTemplate::New(ConsoleLog));
                  ^
V8.cpp:80:76: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     console->Set(String::NewSymbol("log"), FunctionTemplate::New(ConsoleLog));
                                                                            ^
V8.cpp:80:76: note: candidate is:
In file included from V8.cpp:16:0:
/usr/include/v8.h:3696:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/usr/include/v8.h:3696:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
V8.cpp:81:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     console->Set(String::NewSymbol("warn"), FunctionTemplate::New(ConsoleWarn));
                  ^
V8.cpp:81:78: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     console->Set(String::NewSymbol("warn"), FunctionTemplate::New(ConsoleWarn));
                                                                              ^
V8.cpp:81:78: note: candidate is:
In file included from V8.cpp:16:0:
/usr/include/v8.h:3696:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/usr/include/v8.h:3696:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
V8.cpp:82:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     console->Set(String::NewSymbol("error"), FunctionTemplate::New(ConsoleError));
                  ^
V8.cpp:82:80: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     console->Set(String::NewSymbol("error"), FunctionTemplate::New(ConsoleError));
                                                                                ^
V8.cpp:82:80: note: candidate is:
In file included from V8.cpp:16:0:
/usr/include/v8.h:3696:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/usr/include/v8.h:3696:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
V8.cpp:85:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     global->Set(String::NewSymbol("print"), FunctionTemplate::New(ConsoleLog));
                 ^
V8.cpp:85:77: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     global->Set(String::NewSymbol("print"), FunctionTemplate::New(ConsoleLog));
                                                                             ^
V8.cpp:85:77: note: candidate is:
In file included from V8.cpp:16:0:
/usr/include/v8.h:3696:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/usr/include/v8.h:3696:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
V8.cpp:88:46: error: no matching function for call to ‘v8::Context::New(NULL, v8::Handle<v8::ObjectTemplate>&)’
   lstail->context = Context::New(NULL, global);
                                              ^
V8.cpp:88:46: note: candidate is:
In file included from V8.cpp:16:0:
/usr/include/v8.h:5751:25: note: static v8::Local<v8::Context> v8::Context::New(v8::Isolate*, v8::ExtensionConfiguration*, v8::Handle<v8::ObjectTemplate>, v8::Handle<v8::Value>)
   static Local<Context> New(
                         ^
/usr/include/v8.h:5751:25: note:   no known conversion for argument 2 from ‘v8::Handle<v8::ObjectTemplate>’ to ‘v8::ExtensionConfiguration*’
/usr/include/v8.h: In function ‘bool context_enable_typed_arrays(Rcpp::XPtr<v8::Persistent<v8::Context> >)’:
/usr/include/v8.h:832:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
V8.cpp:97:15: error: within this context
   HandleScope handle_scope;
               ^
V8.cpp:98:36: error: no matching function for call to ‘v8::Context::Scope::Scope(v8::Persistent<v8::Context>&)’
   Context::Scope context_scope(*ctx);
                                    ^
V8.cpp:98:36: note: candidates are:
In file included from V8.cpp:16:0:
/usr/include/v8.h:5849:24: note: v8::Context::Scope::Scope(v8::Handle<v8::Context>)
     explicit V8_INLINE Scope(Handle<Context> context) : context_(context) {
                        ^
/usr/include/v8.h:5849:24: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Context>’ to ‘v8::Handle<v8::Context>’
/usr/include/v8.h:5847:9: note: v8::Context::Scope::Scope(const v8::Context::Scope&)
   class Scope {
         ^
/usr/include/v8.h:5847:9: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Context>’ to ‘const v8::Context::Scope&’
V8.cpp:99:40: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Context>’
   v8_typed_array::AttachBindings((*ctx)->Global());
                                        ^
In file included from V8.cpp:16:0:
/usr/include/v8.h: In function ‘std::string context_eval(std::string, Rcpp::XPtr<v8::Persistent<v8::Context> >)’:
/usr/include/v8.h:832:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
V8.cpp:115:15: error: within this context
   HandleScope handle_scope;
               ^
V8.cpp:116:36: error: no matching function for call to ‘v8::Context::Scope::Scope(v8::Persistent<v8::Context>&)’
   Context::Scope context_scope(*ctx);
                                    ^
V8.cpp:116:36: note: candidates are:
In file included from V8.cpp:16:0:
/usr/include/v8.h:5849:24: note: v8::Context::Scope::Scope(v8::Handle<v8::Context>)
     explicit V8_INLINE Scope(Handle<Context> context) : context_(context) {
                        ^
/usr/include/v8.h:5849:24: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Context>’ to ‘v8::Handle<v8::Context>’
/usr/include/v8.h:5847:9: note: v8::Context::Scope::Scope(const v8::Context::Scope&)
   class Scope {
         ^
/usr/include/v8.h:5847:9: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Context>’ to ‘const v8::Context::Scope&’
V8.cpp:123:5: error: ‘AsciiValue’ is not a member of ‘v8::String’
     String::AsciiValue exception_str(exception);
     ^
V8.cpp:124:34: error: ‘exception_str’ was not declared in this scope
     throw std::invalid_argument(*exception_str);
                                  ^
V8.cpp:131:5: error: ‘AsciiValue’ is not a member of ‘v8::String’
     String::AsciiValue exception_str(exception);
     ^
V8.cpp:132:31: error: ‘exception_str’ was not declared in this scope
     throw std::runtime_error(*exception_str);
                               ^
In file included from V8.cpp:16:0:
/usr/include/v8.h: In function ‘bool context_validate(std::string, Rcpp::XPtr<v8::Persistent<v8::Context> >)’:
/usr/include/v8.h:832:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
V8.cpp:148:15: error: within this context
   HandleScope handle_scope;
               ^
V8.cpp:149:36: error: no matching function for call to ‘v8::Context::Scope::Scope(v8::Persistent<v8::Context>&)’
   Context::Scope context_scope(*ctx);
                                    ^
V8.cpp:149:36: note: candidates are:
In file included from V8.cpp:16:0:
/usr/include/v8.h:5849:24: note: v8::Context::Scope::Scope(v8::Handle<v8::Context>)
     explicit V8_INLINE Scope(Handle<Context> context) : context_(context) {
                        ^
/usr/include/v8.h:5849:24: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Context>’ to ‘v8::Handle<v8::Context>’
/usr/include/v8.h:5847:9: note: v8::Context::Scope::Scope(const v8::Context::Scope&)
   class Scope {
         ^
/usr/include/v8.h:5847:9: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Context>’ to ‘const v8::Context::Scope&’
/usr/include/v8.h: In function ‘bool context_assign_bin(std::string, Rcpp::RawVector, Rcpp::XPtr<v8::Persistent<v8::Context> >)’:
/usr/include/v8.h:832:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
V8.cpp:197:15: error: within this context
   HandleScope handle_scope;
               ^
V8.cpp:198:36: error: no matching function for call to ‘v8::Context::Scope::Scope(v8::Persistent<v8::Context>&)’
   Context::Scope context_scope(*ctx);
                                    ^
V8.cpp:198:36: note: candidates are:
In file included from V8.cpp:16:0:
/usr/include/v8.h:5849:24: note: v8::Context::Scope::Scope(v8::Handle<v8::Context>)
     explicit V8_INLINE Scope(Handle<Context> context) : context_(context) {
                        ^
/usr/include/v8.h:5849:24: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Context>’ to ‘v8::Handle<v8::Context>’
/usr/include/v8.h:5847:9: note: v8::Context::Scope::Scope(const v8::Context::Scope&)
   class Scope {
         ^
/usr/include/v8.h:5847:9: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Context>’ to ‘const v8::Context::Scope&’
V8.cpp:199:41: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Context>’
   v8::Handle<v8::Object> global = (*ctx)->Global();
                                         ^
V8.cpp:202:32: error: ‘New’ is not a member of ‘v8::String’
   Local<v8::String> mystring = v8::String::New((const char*) RAW(data), data.length());
                                ^
V8.cpp:203:15: error: ‘NewSymbol’ is not a member of ‘v8::String’
   global->Set(String::NewSymbol(name.c_str()), mystring);
               ^
In file included from V8.cpp:16:0:
/usr/include/v8.h: In function ‘Rcpp::RawVector context_get_bin(std::string, Rcpp::XPtr<v8::Persistent<v8::Context> >)’:
/usr/include/v8.h:832:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
V8.cpp:214:15: error: within this context
   HandleScope handle_scope;
               ^
V8.cpp:215:36: error: no matching function for call to ‘v8::Context::Scope::Scope(v8::Persistent<v8::Context>&)’
   Context::Scope context_scope(*ctx);
                                    ^
V8.cpp:215:36: note: candidates are:
In file included from V8.cpp:16:0:
/usr/include/v8.h:5849:24: note: v8::Context::Scope::Scope(v8::Handle<v8::Context>)
     explicit V8_INLINE Scope(Handle<Context> context) : context_(context) {
                        ^
/usr/include/v8.h:5849:24: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Context>’ to ‘v8::Handle<v8::Context>’
/usr/include/v8.h:5847:9: note: v8::Context::Scope::Scope(const v8::Context::Scope&)
   class Scope {
         ^
/usr/include/v8.h:5847:9: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Context>’ to ‘const v8::Context::Scope&’
V8.cpp:216:41: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Context>’
   v8::Handle<v8::Object> global = (*ctx)->Global();
                                         ^
V8.cpp:219:44: error: ‘NewSymbol’ is not a member of ‘v8::String’
   Local<v8::String> mystring = global->Get(String::NewSymbol(name.c_str()))->ToString();
                                            ^
V8.cpp:221:13: error: ‘class v8::String’ has no member named ‘WriteAscii’
   mystring->WriteAscii((char*) res.begin());
             ^
In file included from V8.cpp:16:0:
/usr/include/v8.h: In instantiation of ‘static void v8::NonCopyablePersistentTraits<T>::Uncompilable() [with O = v8::Object; T = v8::Context]’:
/usr/include/v8.h:611:17:   required from ‘static void v8::NonCopyablePersistentTraits<T>::Copy(const v8::Persistent<S, M>&, v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent*) [with S = v8::Context; M = v8::NonCopyablePersistentTraits<v8::Context>; T = v8::Context; v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent = v8::Persistent<v8::Context>]’
/usr/include/v8.h:6314:21:   required from ‘void v8::Persistent<T, M>::Copy(const v8::Persistent<S, M>&) [with S = v8::Context; M2 = v8::NonCopyablePersistentTraits<v8::Context>; T = v8::Context; M = v8::NonCopyablePersistentTraits<v8::Context>]’
/usr/include/v8.h:676:14:   required from ‘v8::Persistent<T, M>::Persistent(const v8::Persistent<T, M>&) [with T = v8::Context; M = v8::NonCopyablePersistentTraits<v8::Context>]’
V8.cpp:22:8:   required from here
/usr/include/v8.h:615:5: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
     TYPE_CHECK(O, Primitive);
     ^
/usr/lib64/R/etc/Makeconf:142: recipe for target 'V8.o' failed
make: *** [V8.o] Error 1
ERROR: compilation failed for package ‘V8’
* removing ‘/tmp/RtmpqDns3X/devtools_install_1eb8118166e6/V8’
Error: Command failed (1)
Execution halted

Exited with status 1/

**Comment by jeroenooms** [comment]
Probably wrong version of libv8. Which Linux are you using?

**Comment by MikeTuffin** [comment]
Arch. Just installed http://aur.archlinux.org/packages/ruby-libv8/

**Comment by jeroenooms** [comment]
Duplicate https://github.com/jeroenooms/V8/issues/10 ?

**Comment by MikeTuffin** [comment]
Completely missed that, must search harder next time.  Thanks.
