### ISSUE TITLE
V8 on windows XP

### ISSUE THREAD

**Issue by sckott** [jeroenooms/V8#12]
@jeroenooms  Any thoughts on installing V8 on Windows XP?  from https://github.com/ropensci/geojsonio/issues/55

**Comment by jeroenooms** [comment]
Lets try https://github.com/jeroenooms/V8/commit/e6de3420fa61cd12db3844bb1e3967346107cf25.

**Comment by jeroenooms** [comment]
Actually I am reverting this because it breaks the build on modern versions of windows. But @justa9 should be able to get this to work by [adding `-lmsvcr100` to `PKG_LIBS` in `Makevars.win`](https://github.com/jeroenooms/V8/commit/e6de3420fa61cd12db3844bb1e3967346107cf25).

**Comment by sckott** [comment]
Thanks for digging in to this more @jeroenooms - i'll verify this on the xp box

**Comment by sckott** [comment]
@jeroenooms how did you get the sysreq's https://github.com/jeroenooms/V8/blob/master/DESCRIPTION#L16 installed on XP?

**Comment by jeroenooms** [comment]
The windows builds for `libv8` are included in the github repo.

**Comment by justa9** [comment]
Apologies for the delay

I confirm! All work nicely!

Thanks a lot @sckott and @jeroenooms for not giving up!

**Comment by sckott** [comment]
great! glad to hear @justa9
