### ISSUE TITLE
static libraries for windows 

### ISSUE THREAD

**Issue by taylorruss** [jeroenooms/V8#14]
Hi,

Was this issue resolved? 
What is the best way to build static libraries for use with Roots?

Thanks, TR

**Comment by jeroenooms** [comment]
The static libraries are included in the repo with instructions: https://github.com/jeroenooms/V8/tree/master/windows/libv8-3.14.5

**Comment by jeroenooms** [comment]
You shouldn't worry about this, the package automatically pulls in and links libv8 on windows platforms.

**Comment by taylorruss** [comment]
thanks for the quick response. I am facing a similar problem.  I need to build static library for Rtools but -m64 does not seem to work.

**Comment by jeroenooms** [comment]
Which library is it? You can try to grab a gcc build which natively targets win64 from [mingwbuilds](https://sourceforge.net/projects/mingwbuilds/) and use that one to build your static libs.

**Comment by taylorruss** [comment]
great. metis.  thanks again for the very quick response. will do.

**Comment by jeroenooms** [comment]
Is your r package open source? Let me know if you get stuck, I can have a go at it.
