### ISSUE TITLE
Any way to hold a V8 context in package namespace?

### ISSUE THREAD

**Issue by renkun-ken** [jeroenooms/V8#17]
I put a `js_context <- V8::new_context(global = "window")` in the package namespace. But when I use it in a package function, an error occurs saying

```
Error: Context has been disposed. 
```

Is there a way to hold a V8 context to avoid repeatedly creating a new context with the same script sourced every time?

**Comment by jeroenooms** [comment]
No, unfortunately v8 contexts cannot be serialized. However the overhead of creating a new context and sourcing some code is really small, so recreating it should be just as fast. 

Have a look at some R packages that use V8 such as minimist or rjade.

**Comment by renkun-ken** [comment]
Thanks!

**Comment by timelyportfolio** [comment]
just for reference, there was a similar discussion https://github.com/edwindj/daff/issues/1
