### ISSUE TITLE
source method not loading correctly a script

### ISSUE THREAD

**Issue by jbkunst** [jeroenooms/V8#18]
Hi @jeroenooms 

First of all, thanks for this package! It rocks!

I have a problem. I'm trying to load and library (https://github.com/nmrugg/stockfish.js) in a context:

```r
library("V8")
ct <- new_context()
ct$source("stockfish.js") # no error
ct$eval("var stockfish = STOCKFISH();") 
```
And i get: 
```
Error: ReferenceError: setTimeout is not defined
```
I guess the problem is because the file ([stockfish.js](https://github.com/nmrugg/stockfish.js/blob/master/src/stockfish.js)) is too big and minified, but im not sure (or the error is becuse I'm using windows :worried:). Do you have any idea what is happening? 

I can replicate with no problem in a html file:
```html
 <script src="stockfish.js"></script>
  <script>
    var stockfish = STOCKFISH();
    stockfish.onmessage = function(event) { console.log(event.data ? event.data : event);};
    stockfish.postMessage("go depth 2");
    stockfish.postMessage("position fen r3kb1r/1pBnp1pp/p4p2/1N1n1b2/2BP4/5NP1/P4P1P/R1R3K1 w kq - 0 17");
    stockfish.postMessage("go depth 5");
  </script>
```

Thank again for your work!

**Comment by ateucher** [comment]
I can chime in here, but I am by no means an expert. I've run into the same issue with my [rmapshaper](https://github.com/ateucher/rmapshaper) project. `setTimeout` (and `setImmediate` are not available in the `V8` library, though they are defined in `node` and in browsers.

In my case, I tried to find a way to get the timers functions into the `V8` environment but had no luck (Perhaps @jeroenooms has a way). In the end, we were able to tweak the source javascript code to avoid calls to `setTimeout` and `setImmediate`: https://github.com/ateucher/rmapshaper/tree/master/inst/mapshaper.

**Comment by jeroenooms** [comment]
Andy is right, the `setTimeout` function is part of the event-loop which is not in the V8 standard library. See also [this vignette](https://cran.r-project.org/web/packages/V8/vignettes/npm.html). Sometimes you can cheat a bit, for example we can define a stub for `setTimeout`:

```r
ctx <- V8::new_context()
ctx$eval('function setTimeout(){}')
ctx$source("https://raw.githubusercontent.com/nmrugg/stockfish.js/master/src/stockfish.js")
ctx$eval("var stockfish = STOCKFISH();") 
```

This seems to work, but of course it will lead to trouble when the code actually needs `setTimeout`.

**Comment by jbkunst** [comment]
@ateucher @jeroenooms 

Thanks a lot for the responses. It's all more clear now for me.

Regards,
