### ISSUE TITLE
invoke R

### ISSUE THREAD

**Issue by schloerke** [jeroenooms/V8#20]
Hello!

I'm curious if it is possible to have V8 invoke R.  

Situation.  I have a "render" function.  This function needs time sensitive context within R.  When this javascript render function is executed, it will call R which will then return a json blob that the js can understand.

I know this is possible with C.  Didn't know if it could be possible with the V8 context.

Thank you,
Barret

**Comment by b-long** [comment]
I'm not sure if @jeroenooms would agree, but check out https://github.com/Planeshifter/node-Rstats .  Report back if you do :smile:

**Comment by schloerke** [comment]
This might work!.  V8 allows R to be in the driver seat, but rstats might allow V8 to ask questions while "rendering'. 

*looking into now

**Comment by jeroenooms** [comment]
Not sure I understand. Why can't you just pass the object as an argument from R to V8? The state of the R session won't change in between you invoking the v8 context and processing the js...

**Comment by schloerke** [comment]
context: I'm trying to implement a graphql server within R.  The ultimate goal would be to have an interface like this (https://github.com/matthewmueller/graph.ql#example) within R.  V8 is great when used as a wrapper to call the parser command, but I'd rather not implement the rest of graphql requirements.  

The problem arises when calling the evaluation functions.  For example, the data could exist outside of R (such as mysql or something) and it can't be shipped to V8.  R could answer the evaluation questions that graphql would have, and finally the overall function evaluation within V8 would return to the original R session.

Goal: try really hard to not implement the full standard and just use a fully functional and vetted library. Unfortunately, communication needs to happen in both directions for this to happen.

Ideas?

**Comment by schloerke** [comment]
@b-long, trying to load rstats into V8 through browserify and they appear to not be friends right now.  I'm not surprised as V8 is not a full node-js implementation. :-/

**Comment by jeroenooms** [comment]
I'm not familar with graphql, but there is no way to split up the javascript in two parts? So R first calls a javascript function in V8 which then returns whatever it is that you need to get the data. Then in R you perform your query and then the output you push back to V8 in a second call?

I have a hard time understanding what it is you would be able to do when V8 would call R, that you cannot do by having V8 return control to R, do your R stuff, and then pass it in as an argument to a subsequent call to V8.

**Comment by schloerke** [comment]
would V8 allow for a http REST call? (with some npm package).  I think my problem could be solved that way

**Comment by jeroenooms** [comment]
No, V8 has no I/O, all networking/disk access has to be done in R. V8 is just plain javascript...

**Comment by schloerke** [comment]
:-/. Ok. Worth a try.  

I'll see what I can do to get around my issue then.  

I'd like to split up the code, but if I'm using the graphql js library, that isn't possible.

**Comment by jeroenooms** [comment]
We can try to do something in V8 but it is not trivial. How would you imagine this would look? In JavaScript something like:

```r
var out = eval_r("stats::rnorm", {n: 10, mean : 5})
```

But of course this has limitations:

 - You can only call R functions that are visible from the global namespace
 - Arguments and return value are in JSON

**Comment by schloerke** [comment]
That would work great. I would imagine it to be implemented just like that.  The limitations make sense.

For now, I'm looking into R6 classes to see if I can port the JS library code.  I should know more by the end of the week.  I'm going to close the issue for now, so I don't pull everyone along in my wild goose chase.

**Comment by jeroenooms** [comment]
I have added an experimental R callback interface. Can you give this a try. Just start the console as usual:

```r
ctx <- V8::v8()
ctx$console()
```

And then you can call R via `console.R.call`, which maps to `do.call` in R. So the first argument is a function (supplied as a string) and the second argument is a list with arguments, either named or unnamed. Some examples:

```js
//arguments named or unnamed
var out = console.R.call("rnorm", {n: 2,mean:10, sd:5})
var out = console.R.call("rnorm", [2, 10, 5])

//call in package
var out = console.R.call("stats::rnorm", [5])

//literal functions
console.R.call("function(x){x^2}", {x:12})
```

**Comment by schloerke** [comment]
Wow ok!!! I'll be in the office in an couple hours. I'll try then!

**Comment by schloerke** [comment]
works like a expected!

I'm doing this example: 
```{r}
my_func <- function(obj) {
  for (i in 1:3) {
    Sys.sleep(1)
    cat(i, "\n")
  }
  obj$A
}
ctx$eval("
  var obj = {A: \"hi\", B: \"hello\"}; 
  var ans = console.r.call(\"my_func\", {obj: obj}); 
  console.log(\"done\");
  ans
")
# 1 
# 2 
# 3 
# done
# [1] "hi"
```

I'll run it through my more rigorous use case today! :-)

If this works, it will save me months of work and tons of future maintenance.  Thank you.

(If possible, can you set the default value for the console.r.call args to be {}? When it's not supplied, JSON.stringify doesn't know how to deal with undefined.)

**Comment by jeroenooms** [comment]
I have updated the API a bit. Here more examples:

```
//call function without arguments
var out = console.r.call("Sys.time")

//arguments can be named or unnamed
var out = console.r.call("rnorm", {n: 2,mean:10, sd:5})
var out = console.r.call("rnorm", [2, 10, 5])

//call function from package
var out = console.r.call("stats::rnorm", [5])

//literal functions
console.r.call("function(x){x^2}", {x:12})
```

Some new stuff:

```r
//evaluate code:
var out = console.r.eval("rnorm(10)")

//get an object
var iris = console.r.get("iris")
```

**Comment by jeroenooms** [comment]
OK I've added unit tests, I guess this is an official feature now: https://github.com/jeroenooms/V8/blob/master/tests/testthat/test_callback.R.

Closing this topic, please feel free to open new ones with additional problems/suggetions.

**Comment by schloerke** [comment]
Thank you for the addition! Much appreciated!

When I get a full example up and running, I'll point it your way.

**Comment by jeroenooms** [comment]
This stuff is on cran now. Here is the official announcement: https://www.opencpu.org/posts/v8-release-0-10/. Thanks again @schloerke and @eddelbuettel.
