### ISSUE TITLE
Cannot install V8: ANTICONF error

### ISSUE THREAD

**Issue by rgayler** [jeroenooms/V8#22]
I was trying to update the V8 package from 0.9 to 0.10 on Ubuntu 14.04 (64 bit). Obviously 0.9 was previously installed OK. The update failed with the ANTICONF error.
```
Package libv8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libv8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libv8' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lv8
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libv8 was not found. Try installing:
 * deb: libv8-3.14-dev | libv8-dev (Debian, Ubuntu)
 * rpm: v8-devel (Fedora, EPEL)
 * brew: v8-315 (OSX) -- NOT regular v8! Tap from homebrew/versions
 * csw: libv8_dev (Solaris)
If libv8 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libv8.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
```
This behaviour was observed in Rstudio 0.99.876 and 0.99.878 with:
```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8       
 [4] LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.3
```

I tried to reproduce the problem in  a VM running Ubuntu 15.10. On that machine the V8 package was not installed in R so I installed V8 0.10 directly rather than upgrading from 0.9. This worked OK.

```
> install.packages("V8")
Installing package into ‘/home/ross/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
--2016-02-06 15:08:16--  https://cran.rstudio.com/src/contrib/V8_0.10.tar.gz
...
* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
Package libv8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libv8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libv8' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lv8
** libs
rm -f *.o *.so
g++ -I/usr/share/R/include      -I"/home/ross/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"  -DV8_DISABLE_DEPRECATIONS -fpic  -O3 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2    -c RcppExports.cpp -o RcppExports.o
...
installing to /home/ross/R/x86_64-pc-linux-gnu-library/3.2/V8/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (V8)
```
This behaviour was observed in Rstudio 0.99.865 and 0.99.878 with:
```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.3
```
Since the install worked and the update didn't, I tried uninstalling V8 0.9 on the Ubuntu 14.04 computer and installing V8 0.10. This failed with the same ANTICONF error, so now I don't have an installation of V8 on that computer. I tried installing V8 0.9 from V8_0.9.tar.gz, but that also failed with the same ANTICONF error.

Both the working (Ubuntu 15.10) and failing (Ubuntu 14.04) V8 installation attempts complain that libv8 can't be found, so I investigated further following the helpful information in the ANTICONF message.
 
- For both computers I confirmed that libv8-dev is installed (and also tried re-installing it).
- For both computers I confirmed that pkg-config is installed (and also tried re-installing it).
- For both computers I confirmed that pkg-config is in one of the directories on PATH and is executable from the command line.
- For both computers I confirmed that PKG_CONFIG_PATH does not exist as an environment variable.
- I searched both computers for *.pc files (found 49 and 32 of them) but libv8.pc doesn't exist on either computer.
- Googling "libv8.pc" only returns a small number of hits, all of them R-related and mentioning the ANTICONF error. None of them points to an actual libv8.pc file. (I am guessing that libv8.pc doesn't actually exist anywhere.)

So, I try to install V8 on two different computers, both complain that libv8 was not found:
```
Package libv8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libv8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libv8' found
```
but one computer goes on to install it anyway while the other stops with an ANTICONF error. What is the ANTICONF error condition looking for that is true on one computer and false on the other computer?

Also, the ANTICONF error suggests:
```
you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
```
Could that message be expanded (or point to an expansion) that indicates how to work out the values for INCLUDE_DIR and LIB_DIR and how to run R CMD INSTALL (I presume there are more arguments needed)?

Thanks.
Ross

**Comment by jeroenooms** [comment]
The configure script has not changed between 0.9 and 0.10: https://github.com/cran/V8/commits/master

Are you sure `libv8-dev` is installed? Maybe you installed the previous version via `apt-get install r-cran-v8`? Try:

```
apt-get install libv8-dev
```

**Comment by rgayler** [comment]
Thanks, Jeroen, that wasn't the problem, but I solved it by executing your
configure script one line at a time by hand.

The root cause was that g++ wasn't installed! (I'll come back to that
soon.)*

The key line in your configure script is:

> ${CXX} ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -E tools/version.cpp >/dev/null
> 2>&1 || R_CONFIG_ERROR=1;
>

If I try the following modified line I get a nice error message pinpointing
the problem.

> ${CXX} ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -E tools/version.cpp
> >/dev/null
> The program 'g++' is currently not installed. You can install it by typing:
> sudo apt-get install g++
>

Unfortunately, the full line sends the error message to /dev/null. Then the
next section

> # Customize the error
> if [ $R_CONFIG_ERROR ]; then ...
>
effectively assumes that the compilation can only fail for reasons related
to pkg-config, so the generated error message is misleading.


   - Perhaps it would be better to drop the "2>&1" from the compilation
   command so that the error message is visible.
   - It also might be better to make the ANTICONF error message conditional
   on the existence of pkg-config and the values retrieved by pkg-config
   (which you calculate earlier in the script) rather than conditional on the
   compiler error, which can be due to another cause (as in this case).


* How about that missing g++? Well, I didn't intentionally remove it. In
fact, I regularly find out from R package update error messages that g++
and/or gfortran are uninstalled. The difference in this case is that the
error message had gone to /dev/null. I clean up my Ubuntu system regularly,
so I suspect that the cleanup tool I use may remove dev tools like
compilers (sigh). If it does occur as an unintended consequence of some
tool then it probably happens for some other people too.

Cheers and thanks for the useful packages.

Ross

**Comment by nikolai-b** [comment]
```sh
$ sudo aptitude install libv8-dev
libv8-dev is already installed at the requested version (3.14.5.8-8.1)
```
