### ISSUE TITLE
Closing V8 session?

### ISSUE THREAD

**Issue by longouyang** [jeroenooms/V8#25]
I'd like to be able to kill a V8 session -- is that currently supported?

**Comment by jeroenooms** [comment]
If you delete it, the garbage collector will clean it up.

**Comment by longouyang** [comment]
Does that also terminate the V8 process?

**Comment by jeroenooms** [comment]
There is no V8 process; the context runs within the R process.

**Comment by longouyang** [comment]
Ah I see -- thanks.
