### ISSUE TITLE
V8 broken in Fedora 25

### ISSUE THREAD

**Issue by rsbivand** [jeroenooms/V8#30]
Fedora 25 ships with 5.2, so tools/version.cpp wrongly shows ANTICONF ERROR on source install. Error message not displayed from tools/version.cpp. 

On Fedora 25, you need to install v8-314-devel, which clashes with v8-devel (so other software may get broken), and needs:

`--configure-vars='INCLUDE_DIR=/usr/include/v8-3.14 LIB_DIR=/usr/lib64'`

**Comment by jeroenooms** [comment]
Are you talking about the CRAN version? The development version of the R package already mentions `v8-314-devel` in the configure script. I should improve the error message when libv8 is found but has the wrong version. 

 I think `pkg-config` should automatically set the correct `INCLUDE_DIR` and `LIB_DIR`...

**Comment by rsbivand** [comment]
CRAN version. I don't use V8, but packages suggesting etc. rgdal and rgeos do, so I like to keep my dependency checking up to date through update.packages() which obviously uses CRAN. This was rgbif error exiting update.packages(). I only ever install from GH when I actively need to see the development version of a package I'm helping (and then by cloning locally and running R CMD build locally).

The Fedora V8 doesn't set pkg-config (possibly because of the muddle with versions - from the client side it is v8.h and libv8.so that are required, but the versions are in different places).

**Comment by jeroenooms** [comment]
OK I'll update the script to check for the presence of a `/usr/include/v8-3.14` directory and release a new CRAN version soon to help Fedora users install the correct dependencies.

**Comment by rsbivand** [comment]
Thanks!

**Comment by jeroenooms** [comment]
There is now a new version on CRAN that should work on F25 and give a better error message if the wrong version of libv8 is installed.

**Comment by rsbivand** [comment]
Checked, with v8-314-devel installed on Fedora 25, 1.2 installed fine, without configure.args. Thanks!
