### ISSUE TITLE
Homebrew installation information incomplete

### ISSUE THREAD

**Issue by bernhardvogler** [jeroenooms/V8#31]
Simply running `brew install v8-315` is not always sufficient.

It took me quite some time and effort to figure out that you first have to add a versions tap like so: `brew tap homebrew/versions`
Only after that I was able to install v8-315 with Homebrew which then allowed me to install the R package.

I suggest you add this information to the instructions where you ask the user to run the `brew install v8-315` command.

**Comment by jeroenooms** [comment]
This is already noted in the readme and configure file. Where did you not find this information?

**Comment by bernhardvogler** [comment]
When running `install.packages('V8')` and you have the wrong v8 version, these are the instructions for macOS:
```
On MacOS Homebrew try this:
  brew remove v8
  brew install v8-315
```

So in this case there’s no hint regarding the homebrew/versions tap.

However, when you haven’t installed a wrong version, it gives the all the information in the first place: 
`brew: v8-315 (OSX) -- NOT regular v8! Tap from homebrew/versions`
But if you overlook this info (like I did) then the homebrew/versions hint is missing. So it would be cool to add it to the instructions when people have the wrong version.

Anyways, I must say I like the interactive hints regarding the dependency installation. :-)

**Comment by jeroenooms** [comment]
Well the latter was already fixed in the devel version: https://github.com/jeroenooms/V8/commit/7b148a93746a7511c17e3e77edd40147a8ff4bca

**Comment by bernhardvogler** [comment]
Cool!
