### ISSUE TITLE
`emscripten` generated code

### ISSUE THREAD

**Issue by timelyportfolio** [jeroenooms/V8#5]
With `emscripten` generated code, it appears we get an error like https://gist.github.com/kripken/5737516#file-src-cpp-o-js-L676-L677.  Feel free to disregard, but I discovered as I was toying around.

**Comment by jeroenooms** [comment]
Your code uses Typed Arrays [Float64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array) and [Int32Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array) which were introduced recently and are not part of ECMA5. This [post](http://engineering.prezi.com/blog/2013/08/27/embedding-v8/) describes a hack that we might be able to use. 

It would be preferable if you would be able to generated ECMA5 compliant code, but I'm not sure if that is an option in emscripten.

**Comment by jeroenooms** [comment]
@timelyportfolio Do you have an example for me that I can test/reproduce this with?

**Comment by jeroenooms** [comment]
@timelyportfolio I have added experimental support for typed arrays:

```s
ct <- new_context(typed_arrays = TRUE)
ct$eval("Object.keys(global)")
```

Could you give this a test drive?

**Comment by timelyportfolio** [comment]
Great, I'll try to find the old bit of code and also work on some other tests tonight.  Thanks.

**Comment by jeroenooms** [comment]
Ok great. I noticed that some emscripten libraries assume a `print` function, but you can just do something like:

```s
ct$eval("print = console.log")
```

**Comment by timelyportfolio** [comment]
As I have learned to expect from you, it works perfectly. For reference, I was trying viz.js which is an emscripten version of graphviz that we use in `DiagrammeR`.  Here is the code.

```
library(V8)

ct = new_context()
ct$eval ( ' var window = global; ')
ct$source( 'http://mdaines.github.io/viz.js/viz.js' )
( diagram = ct$eval('Viz("digraph { a -> b; }", "svg")') )
```

Then to carry the example even farther, we can look at it versus the `DiagrammeR`-rendered result.

```
# devtools::install_github("rich-iannone/DiagrammeR")
library(DiagrammeR)
library(htmltools)

html_print(tagList(
  grViz( "digraph { a -> b; }" )
  , HTML(diagram)
))
```

**Comment by jeroenooms** [comment]
Cool. It also seem to work with [sql.js](https://github.com/kripken/sql.js/) which is really cool. Let me know if you have any more suggestions!

**Comment by jeroenooms** [comment]
By the way, a shorter way to write down your code is as follows:

```s
library(V8)
ct <- new_context("window")
invisible(ct$source( 'http://mdaines.github.io/viz.js/viz.js' ))
diagram = ct$call("Viz", "digraph { a -> b; }", "svg")
```

**Comment by timelyportfolio** [comment]
Awesome, I was not aware the new `new_context(...)` syntax.  Thanks for the tip and the very handy parameter.  Two other emscriptens that I thought interesting but not yet tried are https://github.com/antimatter15/ocrad.js and https://github.com/trevorlinton/webkit.js.  `sql.js` will be very interesting and once again require to change my mindset before I can think of the new possibilities.  I look forward to that.

**Comment by timelyportfolio** [comment]
I guess I can close this now, since you have fixed and we have tested in a couple places.  Thanks.
